### GetMemberById
GRPC localhost:50051/MemberService/GetMemberById

{
  "id": 8
}

### CreateMember
GRPC localhost:50051/MemberService/CreateMember

{
  "email": "tes2t25s2@example.com",
  "password": "1234",
  "name": "Test User",
  "profilePictureUrl": "http://example.com/profile.jpg",
  "introduction": "Hello, I am a test user.",
  "phoneNumber": "123-456-7890",
  "address": "123 Test Street, Test City, TX 12345",
  "birthDate": "1990-01-01T00:00:00",
  "gender": "Male",
  "website": "http://example.com",
  "statusMessage": "Feeling good!",
  "accountStatus": "Active",
  "joinedDate": "2024-06-29T13:00:00",
  "lastLogin": "2024-06-29T13:30:00"
}