spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/member
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

server:
  port: 8081