# 포트 설정
server:
  port: 8081

logging:
  level:
    org.springframework.boot.context.properties: DEBUG

# 스프링 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/member
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    database: POSTGRESQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  # 카프카 설정
  kafka:
    consumer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
      group-id: member-group
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

grpc:
  server:
    port: 50051  # gRPC 서버 포트 설정